# Generated by Django 2.0.4 on 2019-04-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190408_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='resume',
        ),
    ]
