# Generated by Django 2.1.7 on 2019-05-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_applicationmodel_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='graduate',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='professional',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
