# Generated by Django 2.1.7 on 2019-05-28 20:32

import application.formatChecker
import application.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20190520_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='resume',
            field=application.formatChecker.ContentTypeRestrictedFileField(upload_to=application.models.get_file_path),
        ),
    ]
