# Generated by Django 2.1.7 on 2019-05-28 20:49

import application.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20190528_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='resume',
            field=application.formatChecker.ContentTypeRestrictedFileField(upload_to='resume'),
        ),
    ]
