# Generated by Django 2.1.7 on 2019-05-28 21:12

import application.formatChecker
import application.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20190528_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='resume',
            field=application.formatChecker.ContentTypeRestrictedFileField(upload_to=application.models.get_file_path),
        ),
    ]
