# Generated by Django 2.2 on 2019-04-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='text',
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='first_name',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
