# Generated by Django 2.2 on 2019-04-08 02:14

import application.formatChecker
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190408_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='attended',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='birthday',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='city',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='conduct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='country',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='education',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='email',
            field=models.EmailField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='essay1',
            field=models.CharField(default='-', max_length=350),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='essay2',
            field=models.CharField(default='-', max_length=350),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='essay3',
            field=models.CharField(default='-', max_length=350),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='essay4',
            field=models.CharField(default='-', max_length=350),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='gender',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='graduating_class',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='how_heard_medhacks',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='last_name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='major',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='permission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='phone_number',
            field=models.CharField(blank=True, default='-', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='race',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='reimbursement',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='resume',
            field=application.formatChecker.ContentTypeRestrictedFileField(default=django.utils.timezone.now, upload_to='resume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='secondmajor',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='state',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='university',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
