# Generated by Django 2.1.7 on 2019-04-24 19:40

import application.formatChecker
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_applicationmodel_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='resume',
            field=application.formatChecker.ContentTypeRestrictedFileField(default=django.utils.timezone.now, upload_to='resume'),
            preserve_default=False,
        ),
    ]
