# Generated by Django 2.0.4 on 2019-07-16 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelappmodel',
            old_name='contingency',
            new_name='contribution_essay',
        ),
    ]
